services:
  rtsp-to-onvif:
    build: .
    image: mountaindude/rtsp-to-onvif:latest
    hostname: rtsp-to-onvif
    restart: unless-stopped
    volumes:
      - ./config.yaml:/onvif.yaml
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    environment:
      DEBUG: 1  # Set to 0 (or remove) to disable debug logging
