services:
  rtsp-to-onvif:
    image: ptarmiganlabs/rtsp-to-onvif:latest
    # Alternative: pull from GitHub Container Registry
    # image: ghcr.io/ptarmiganlabs/rtsp-to-onvif:latest
    hostname: rtsp-to-onvif
    restart: unless-stopped
    volumes:
      - ./config.yaml:/onvif.yaml
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    environment:
      DEBUG: 0 # Set to 1 or true to enable debug logging
